name: chat_app
description: "Main Chat Application."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

  design_system:
    path: ../../packages/design_system

  feature_chat_list:
    path: ../../packages/feature_chat_list

  # --- Architecture & State
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  # --- Navigation
  go_router: ^17.0.0
  # --- DI
  get_it: ^9.1.1
  injectable: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Gen
  build_runner: ^2.4.8
  injectable_generator: ^2.11.0

flutter:
  uses-material-design: true
  generate: true